services:

  yorznab:
    image: python:3.11-slim
    container_name: yorznab
    user: "1000:1000" # Optional, user:group
    environment:
      - TZ=UTC # Set your local timezone for accurate cron schedules
      - HOME=/tmp # Python installation directory, change to /home for root user
      - PYTHONUNBUFFERED=1 # Real-time logging
      - CONFIG_DIR=/app/config # Edit these files HERE: config.yaml, yorznab.yaml, filters.yaml (optional)
      - LOG_DIR=/logs # Default is the temp directory
      #- SECURE_APPID=YOUR_APPID # Change this to prevent unauthorized access of API and webhook credentials via /login?appid=YOUR_APPID
    ports:
      - "9116:8080" # Default port 9116
    extra_hosts:
      - "host.docker.internal:host-gateway" # Expose Yorznab to other containers
    volumes:
      # Only for root user to persist Python installation
      # - /srv/dev/yorznab/python:/home
      # Writing RSS feed
      - type: bind
        source: /srv/dev/yorznab/export/
        target: /export
      # Logging server output
      - type: bind
        source: /srv/dev/yorznab/logs
        target: /logs
      # Writing Yorznab API Keys to keys.yaml
      - type: bind
        source: /srv/dev/yorznab/app/config
        target: /app/config
      # Running the Python web server and cron job
      - type: bind
        source: /srv/dev/yorznab/app/server
        target: /app/server
        read_only: true
    command: >
        bash -c "
        export PYTHONPATH=/app;
        export PATH=\"$$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$$PATH\";
        cd /app/server &&
        pip install --user --upgrade pip &&
        pip install --user -r requirements.txt && 
        python -m uvicorn run:app --host 0.0.0.0 --port 8080;"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import http.client; conn = http.client.HTTPConnection(\"localhost\", 8080); conn.request(\"GET\", \"/status\"); r = conn.getresponse(); exit(0 if r.status < 400 else 1)'"]
      start_period: 20s
      interval: 300s
      timeout: 15s
      retries: 10
    restart: unless-stopped