services:

  yorznab:
    image: python:3.14-slim
    container_name: yorznab
    user: "1000:1000" # Optional, user:group
    environment:
      - TZ=UTC # Set your local timezone for accurate cron schedules
      - HOME=/tmp # Python installation directory, change to /home for root user
      - LOG_DIR=/logs # Persist logs on the filesystem, or leave blank to use the temp directory
      - LOG_LEVEL=INFO # Set logging level (default=DEBUG): DEBUG, INFO, WARNING, ERROR, CRITICAL (no logs)
    ports:
      - "9116:9116" # Default port 9116
    extra_hosts:
      - "host.docker.internal:host-gateway" # Expose Yorznab to other containers
    volumes:
      # Only for root user to persist Python installation
      # - /path/to/yorznab/python:/home
      # Logging server output
      - type: bind
        source: /path/to/yorznab/logs
        target: /logs
      # Writing Yorznab API Keys to keys.yaml
      - type: bind
        source: /path/to/yorznab/app/config
        target: /app/config
      # Running the Python web server and cron job
      - type: bind
        source: /path/to/yorznab/app/server
        target: /app/server
        read_only: true
    command: >
        bash -c "
        export PYTHONUNBUFFERED=1;
        export PYTHONPATH=/app;
        export PATH=\"$$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$$PATH\";
        cd /app/server &&
        pip install --user --upgrade pip &&
        pip install -e . &&
        yorznab;"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; exit(0 if urllib.request.urlopen('http://localhost:9116/api/status').getcode() < 400 else 1)\""]
      start_period: 20s
      interval: 300s
      timeout: 15s
      retries: 10
    restart: unless-stopped