from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Type, TypeVar
import httpx

# Import classes
from server.entities.YorznabClient import YorznabClient
from server.routers.handler import RouteHandler
from server.routers.torznab import CAT_LOOKUP, CATEGORIES
from server.entities.BaseClient import BaseClient
from server.utils.keystore import KeyStore

class ArrType(Enum):
    Radarr = "Radarr"
    Sonarr = "Sonarr"

@dataclass
class ArrConfig:
    Url: Optional[str] = field(
        default=None,
        metadata={
            "name": "Arr Server",
            "description": "URL used to connect to the Arr app server, including http(s)://, port, and urlbase if required"
        }
    )
    UrlFrom: Optional[str] = field(
        default_factory=lambda: YorznabClient().Url,
        metadata={
            "name": "Yorznab Server",
            "description": "Yorznab server URL as the Arr app sees it, including http(s)://, port, and urlbase if needed"
        }
    )
    ApiKey: str = field(
        default=None,
        metadata={
            "name": "API Key",
            "required": True,
            "password": True,
            "description": "The ApiKey generated by the Arr app in Settings > General"
        }
    )
    def __post_init__(self):
        """Set default URL based on ServerType if not provided."""
        if self.Url is None:
            if self.ServerType == ArrType.Radarr:
                self.Url = "http://localhost:7878"
            elif self.ServerType == ArrType.Sonarr:
                self.Url = "http://localhost:8989"

@dataclass
class ArrClient(BaseClient[ArrConfig]):

    def __init__(self, server_type: ArrType):
        # Initialize _name and _config_file
        self._server_type = server_type
        super().__init__(name=self.ServerType.value)

    class EndpointType(Enum):
        api = ''
        episode = '/episode' # Sonarr only
        command = '/command'
        indexer = '/indexer'
        queue = '/queue'
        status = '/system/status'
        wanted = '/wanted/missing'

        def __str__(self):
            return self.value

    @dataclass
    class Mapper:
        Radarr: Any
        Sonarr: Any

    T = TypeVar('T')
    def serve(self, mapper: Mapper, value: T = None) -> Type[T]:
        if value is not None: return value
        match self.ServerType:
            case ArrType.Radarr:
                return mapper.Radarr
            case ArrType.Sonarr:
                return mapper.Sonarr
            case _:
                raise ValueError(f"Unknown library server: {self.ServerName}")
    
    @property
    def DefaultUrl(self) -> str: return self.serve(self.Mapper(Radarr="http://localhost:7878", Sonarr="http://localhost:8989"))
    
    @property
    def ServerType(self) -> ArrType: return self._server_type
    
    @property
    def TypeName(self) -> str: return self.serve(self.Mapper(Radarr="Movies", Sonarr="TV"))
    
    @property
    def Headers(self) -> dict[str, str]: return {"X-Api-Key": self.Config.ApiKey}
    
    @property
    def ApiVersion(self) -> str: return '/api/v3'

    def GetEndpoint(self, endpoint: ArrClient.EndpointType) -> str:
        if endpoint == self.__class__.EndpointType.api:
            return self.UrlPath + self.serve(self.Mapper(Radarr="/movie", Sonarr="/series"))
        else:
            return self.UrlPath + str(endpoint)
    
    @property
    def ProperName(self) -> str: return self.serve(self.Mapper(Radarr="Movie", Sonarr="Show"))
    
    @property
    def ProperNames(self) -> str: return self.serve(self.Mapper(Radarr="Movies", Sonarr="Shows"))
    
    @property
    def ExternalDb(self) -> str: return self.serve(self.Mapper(Radarr="tmdb", Sonarr="tvdb"))
    
    @property
    def ExternalId(self) -> str: return self.serve(self.Mapper(Radarr="tmdbId", Sonarr="tvdbId"))

    @property
    def session(self) -> httpx.Client:
        """Get the session, always using singleton"""
        return self._get_session()

    def status(self) -> dict[str, Any]:
        self.LOGGER.info(f"🛜 Pinging {self.ServerName} Arr server")
        resp = self.session.get(self.GetEndpoint(self.EndpointType.status), headers=self.Headers, timeout=self.TIMEOUT_DEFAULT)
        resp.raise_for_status()
        result = resp.json()
        self.LOGGER.info(f"✅ Received ping response from {self.ServerName} Arr server")
        return result
    
    def _paginate(self, endpoint: EndpointType, page_size: int = 250) -> list[dict[str, Any]]:
        """Generic pagination helper that returns all records."""
        page = 1
        records = []
        
        while True:
            params = {"page": page, "pageSize": page_size}
            resp = self.session.get(
                self.GetEndpoint(endpoint),
                headers=self.Headers,
                params=params,
                timeout=self.TIMEOUT_DEFAULT
            )
            resp.raise_for_status()
            result = resp.json()
            
            total_records = result.get("totalRecords", 0)
            new_records = result.get("records", [])
            records.extend(new_records)
            
            if len(records) >= total_records or not new_records:
                break
            
            page += 1
        
        return records

    def wanted_missing(self) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Searching for missing videos.")
        records = self._paginate(self.EndpointType.wanted)
        self.LOGGER.info(f"📺 Found {len(records)} missing {self.ProperNames.lower()}.")
        return records

    def queue(self) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Searching for queued videos.")
        records = self._paginate(self.EndpointType.queue)
        self.LOGGER.info(f"📺 Found {len(records)} queued {self.ProperNames.lower()}.")
        return records

    def get_episodes(self, external_id: str, season_numbers: list[str] = None) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Fetching episodes from {self.ServerName} server.")
        all_episodes = []
        if season_numbers is None:
            season_numbers = ['0']
        for season_number in season_numbers:
            season_filter = ""
            if season_number != '0':
                season_filter = f"&seasonNumber={season_number}"
            url = f"{self.GetEndpoint(self.EndpointType.episode)}?seriesId={external_id}{season_filter}"
            resp = self.session.get(url, headers=self.Headers, timeout=self.TIMEOUT_DEFAULT)
            resp.raise_for_status()
            season = resp.json()
            all_episodes.append(season)
        self.LOGGER.info(f"📺 Fetched {len(all_episodes)} episodes from {'all' if season_numbers == ['0'] else len(season_numbers)} seasons for {self.ExternalId}: {external_id}")
        return all_episodes

    def get_video(self, external_id: str) -> dict[str, Any]:
        self.LOGGER.info(f"🔍 Fetching {self.ProperName} from {self.ServerName} server.")
        url = f"{self.GetEndpoint(self.EndpointType.api)}/{external_id}"
        resp = self.session.get(url, headers=self.Headers, timeout=self.TIMEOUT_DEFAULT)
        resp.raise_for_status()
        data = resp.json()
        self.LOGGER.info(f"📺 Fetched {self.ProperName} from {self.ServerName} server: {data.get('title')}")
        return data

    def update_rss(self) -> dict[str, Any]:
        body = {
            "name": "RssSync"
        }
        self.LOGGER.info(f"🌐 Sending RSS sync command to {self.ServerName} server.")
        resp = self.session.post(self.GetEndpoint(self.EndpointType.command), headers=self.Headers, json=body, timeout=self.TIMEOUT_DEFAULT)
        resp.raise_for_status()
        return resp.json()

    async def create_torznab_indexer(self, feed_name: str) -> dict[str, Any]:

        # Get cat_ids like: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]
        root_id = next(c["id"] for c in CATEGORIES if c["label"] == "Movies")
        category_ids = [c["id"] for c in CATEGORIES if CAT_LOOKUP.get(c["id"]) == root_id]
        print(f"Creating Torznab indexer '{feed_name}' with categories: {category_ids}")
        payload = {
            "name": f"{feed_name} ({YorznabClient().ServerName})",
            "implementation": "Torznab",
            "implementationName": "Torznab",
            "configContract": "TorznabSettings",
            "infoLink": self.Config.UrlFrom,
            "enableRss": True,
            "enableAutomaticSearch": True,
            "enableInteractiveSearch": True,
            "downloadClientId": 0,
            "priority": 25,
            "tags": [],
            "fields": [
                {"name": "baseUrl", "value": self.Config.UrlFrom},
                {"name": "apiPath", "value": RouteHandler.INDEXER + '/' + feed_name},
                {"name": "apiKey", "value": KeyStore.get_key('INDEXER_KEY')},
                {"name": "categories", "value": category_ids},
                {"name": "minimumSeeders", "value": 1},
                {"name": "seedCriteria.seedTime", "value": None},
                {"name": "seedCriteria.seedRatio", "value": None},
                {"name": "rejectBlocklistedTorrentHashesWhileGrabbing", "value": False}
            ]
        }
        
        self.LOGGER.info(f"🔧 Configuring the indexer for {self.ServerName}: {feed_name}")
        response = self.session.post(
            f"{self.UrlPath}{self.EndpointType.indexer}",
            json=payload,
            headers=self.Headers,
            timeout=self.TIMEOUT_DEFAULT
        )
        print(f"Response from {self.ServerName} server: {response.status_code} - {response.text}")
        response.raise_for_status()
        self.LOGGER.info(f"✅ Configured the indexer successfully")
        
        return response.json()

    def delete_torznab_indexer(self, feed: str) -> dict[str, Any]:
        self.LOGGER.info(f"🗑️ Deleting Torznab indexer '{feed}' from {self.ServerName} server.")
        response = self.session.delete(
            f"{self.UrlPath}{self.EndpointType.indexer}/{feed}",
            headers=self.Headers,
            timeout=self.TIMEOUT_DEFAULT
        )
        response.raise_for_status()
        return response.json()
    