from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
import os
from typing import Any, Optional, Type, TypeVar
from dacite import Config, from_dict
from dacite.exceptions import MissingValueError
import httpx

# Import classes
from server import PROJECT_ROOT
from server.entities.Yorznab import YorznabConfig
from server.routers.handler import RouteHandler
from server.routers.torznab import CAT_LOOKUP, CATEGORIES
from server.entities.AppClient import AppClient
from server.utils.customlogger import CustomLogger
from server.utils.keystore import KeyStore
from server.utils.settings import AppSettings, AppSettingsUndefined

class ArrType(Enum):
    Radarr = "Radarr"
    Sonarr = "Sonarr"

@dataclass
class ArrConfig:
    ServerType: ArrType
    Url: Optional[str] = field(
        default=None,
        metadata={
            "name": "Arr Server",
            "description": "URL used to connect to the Arr app server, including http(s)://, port, and urlbase if required"
        }
    )
    UrlFrom: Optional[str] = field(
        default=YorznabConfig().Indexer.Url,
        metadata={
            "name": "Yorznab Server",
            "description": "Yorznab server URL as the Arr app sees it, including http(s)://, port, and urlbase if needed"
        }
    )
    ApiKey: str = field(
        default=None,
        metadata={
            "name": "API Key",
            "required": True,
            "description": "The ApiKey generated by the Arr app in Settings > General"
        }
    )
    def __post_init__(self):
        """Set default URL based on ServerType if not provided."""
        if self.Url is None:
            if self.ServerType == ArrType.Radarr:
                self.Url = "http://localhost:7878"
            elif self.ServerType == ArrType.Sonarr:
                self.Url = "http://localhost:8989"

@dataclass
class ArrClient(AppClient):

    def __init__(self, server_type: ArrType):
        # Initialize _name and _config_file
        super().__init__(name=server_type.value)
        self._config: ArrConfig = None

        self.LOGGER = CustomLogger(name=self._name)
        # Resolve config file settings.yaml
        try:
            config_raw = AppSettings(filename=self._config_file).get()
        except AppSettingsUndefined as e:
            self.LOGGER.warning(f"🚩 Server has bad configuration for {self._name}. Continuing without this app.")
            raise Exception(e)
        config_raw["ServerType"] = self._name
        try:
            self._config = from_dict(data_class=ArrConfig, data=config_raw, config=Config(cast=[ArrType]))
        except MissingValueError as e:
            self.LOGGER.error(f"🚩 Trouble parsing field for {self._name}, check file: {os.path.join(PROJECT_ROOT, self._config_file)}")
            raise Exception(e)

    class EndpointType(Enum):
        api = ''
        episode = '/episode' # Sonarr only
        command = '/command'
        indexer = '/indexer'
        queue = '/queue'
        status = '/system/status'
        wanted = '/wanted/missing'

        def __str__(self):
            return self.value

    @dataclass
    class Mapper:
        Radarr: Any
        Sonarr: Any

    T = TypeVar('T')
    def serve(self, mapper: Mapper, value: T = None) -> Type[T]:
        if value is not None: return value
        match self.ServerType:
            case ArrType.Radarr:
                return mapper.Radarr
            case ArrType.Sonarr:
                return mapper.Sonarr
            case _:
                raise ValueError(f"Unknown library server: {self.ServerName}")
    
    @property
    def ServerName(self) -> str: return self.ServerType.value
    
    @property
    def DefaultUrl(self) -> str: return self.serve(self.Mapper(Radarr="http://localhost:7878", Sonarr="http://localhost:8989"))
    
    @property
    def ServerType(self) -> ArrType: return self._config.ServerType
    
    @property
    def TypeName(self) -> str: return self.serve(self.Mapper(Radarr="Movies", Sonarr="TV"))
    
    @property
    def Headers(self) -> dict[str, str]: return {"X-Api-Key": self._config.ApiKey}
    
    @property
    def ApiVersion(self) -> str: return '/api/v3'
    
    @property
    def Url(self) -> str: return self._config.Url
    
    @property
    def UrlPath(self) -> str: return self.Url + self.ApiVersion
    
    @property
    def UrlFrom(self) -> str: return self._config.UrlFrom

    def GetEndpoint(self, endpoint: ArrClient.EndpointType) -> str:
        if endpoint == self.__class__.EndpointType.api:
            return self.UrlPath + self.serve(self.Mapper(Radarr="/movie", Sonarr="/series"))
        else:
            return self.UrlPath + str(endpoint)
    
    @property
    def ProperName(self) -> str: return self.serve(self.Mapper(Radarr="Movie", Sonarr="Show"))
    
    @property
    def ProperNames(self) -> str: return self.serve(self.Mapper(Radarr="Movies", Sonarr="Shows"))
    
    @property
    def ExternalDb(self) -> str: return self.serve(self.Mapper(Radarr="tmdb", Sonarr="tvdb"))
    
    @property
    def ExternalId(self) -> str: return self.serve(self.Mapper(Radarr="tmdbId", Sonarr="tvdbId"))

    @property
    def session(self) -> httpx.Client:
        """Get the session, always using singleton"""
        return self._get_session()

    def status(self) -> dict[str, Any]:
        self.LOGGER.info(f"🛜 Pinging {self.ServerName} Arr server")
        resp = self.session.get(self.GetEndpoint(self.EndpointType.status), headers=self.Headers, timeout=30)
        resp.raise_for_status()
        result = resp.json()
        self.LOGGER.info(f"✅ Received ping response from {self.ServerName} Arr server")
        return result
    
    def _paginate(self, endpoint: EndpointType, page_size: int = 250) -> list[dict[str, Any]]:
        """Generic pagination helper that returns all records."""
        page = 1
        records = []
        
        while True:
            params = {"page": page, "pageSize": page_size}
            resp = self.session.get(
                self.GetEndpoint(endpoint),
                headers=self.Headers,
                params=params,
                timeout=30
            )
            resp.raise_for_status()
            result = resp.json()
            
            total_records = result.get("totalRecords", 0)
            new_records = result.get("records", [])
            records.extend(new_records)
            
            if len(records) >= total_records or not new_records:
                break
            
            page += 1
        
        return records

    def wanted_missing(self) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Searching for missing videos.")
        records = self._paginate(self.EndpointType.wanted)
        self.LOGGER.info(f"📺 Found {len(records)} missing {self.ProperNames.lower()}.")
        return records

    def queue(self) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Searching for queued videos.")
        records = self._paginate(self.EndpointType.queue)
        self.LOGGER.info(f"📺 Found {len(records)} queued {self.ProperNames.lower()}.")
        return records

    def get_episodes(self, external_id: str, season_numbers: list[str] = None) -> list[dict[str, Any]]:
        self.LOGGER.info(f"🔍 Fetching episodes from {self.ServerName} server.")
        all_episodes = []
        if season_numbers is None:
            season_numbers = ['0']
        for season_number in season_numbers:
            season_filter = ""
            if season_number != '0':
                season_filter = f"&seasonNumber={season_number}"
            url = f"{self.GetEndpoint(self.EndpointType.episode)}?seriesId={external_id}{season_filter}"
            resp = self.session.get(url, headers=self.Headers, timeout=30)
            resp.raise_for_status()
            season = resp.json()
            all_episodes.append(season)
        self.LOGGER.info(f"📺 Fetched {len(all_episodes)} episodes from {'all' if season_numbers == ['0'] else len(season_numbers)} seasons for {self.ExternalId}: {external_id}")
        return all_episodes

    def get_video(self, external_id: str) -> dict[str, Any]:
        self.LOGGER.info(f"🔍 Fetching {self.ProperName} from {self.ServerName} server.")
        url = f"{self.GetEndpoint(self.EndpointType.api)}/{external_id}"
        resp = self.session.get(url, headers=self.Headers, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        self.LOGGER.info(f"📺 Fetched {self.ProperName} from {self.ServerName} server: {data.get('title')}")
        return data

    def update_rss(self) -> dict[str, Any]:
        body = {
            "name": "RssSync"
        }
        self.LOGGER.info(f"🌐 Sending RSS sync command to {self.ServerName} server.")
        resp = self.session.post(self.GetEndpoint(self.EndpointType.command), headers=self.Headers, json=body, timeout=30)
        resp.raise_for_status()
        return resp.json()

    def add_torznab_indexer(self, feed: str) -> dict[str, Any]:

        # Get cat_ids like: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]
        root_id = next(c["id"] for c in CATEGORIES if c["label"] == "Movies")
        category_ids = [c["id"] for c in CATEGORIES if CAT_LOOKUP.get(c["id"]) == root_id]

        payload = {
            "name": YorznabConfig().Indexer.Title,
            "implementation": "Torznab",
            "implementationName": "Torznab",
            "configContract": "TorznabSettings",
            "infoLink": self.UrlFrom,
            "enableRss": True,
            "enableAutomaticSearch": True,
            "enableInteractiveSearch": True,
            "priority": 25,
            "tags": [],
            "fields": [
                {"name": "baseUrl", "value": self.UrlFrom},
                {"name": "apiKey", "value": KeyStore.get_key('INDEXER_KEY')},
                {"name": "apiPath", "value": self.UrlFrom + RouteHandler.INDEXER + '/' + feed},
                {"name": "categories", "value": category_ids},
                {"name": "minimumSeeders", "value": 1},
                {"name": "seedCriteria.seedTime", "value": 0},
                {"name": "seedCriteria.seedRatio", "value": 0.0},
                {"name": "rejectBlocklistedTorrentHashesWhileGrabbing", "value": False}
            ]
        }
        
        response = self.session.post(
            f"{self.UrlPath}{self.EndpointType.indexer}",
            json=payload,
            headers=self.Headers,
            timeout=30
        )
        response.raise_for_status()
        
        return response.json()
