from dataclasses import dataclass, field
from enum import Enum
from typing import Any, List, Optional

from dacite import Config, from_dict
import httpx

# Import classes
from server.entities.YorznabClient import YorznabClient
from server.routers.handler import RouteHandler
from server.entities.BaseClient import BaseClient
from server.entities.ArrClient import ArrType
from server.utils.keystore import KeyStore

@dataclass
class NotificationType(Enum):
    NONE = 0
    MEDIA_PENDING = 2
    MEDIA_APPROVED = 4
    MEDIA_AVAILABLE = 8
    MEDIA_FAILED = 16
    TEST_NOTIFICATION = 32
    MEDIA_DECLINED = 64
    MEDIA_AUTO_APPROVED = 128
    ISSUE_CREATED = 256
    ISSUE_COMMENT = 512
    ISSUE_RESOLVED = 1024
    ISSUE_REOPENED = 2048
    MEDIA_AUTO_REQUESTED = 4096

@dataclass
class WebhookPayload:
    notification_type: str
    media: Optional[dict] = None
    extra: List[dict] = None
    request: Optional[dict] = None
    
    @property
    def is_movie(self) -> bool:
        return self.media is not None and self.media.get("media_type") == "movie"
    
    @property
    def is_tv(self) -> bool:
        return self.media is not None and self.media.get("media_type") == "tv"
    
    @property
    def arr_type(self) -> Optional[ArrType]:
        if self.is_movie:
            return ArrType.Radarr
        elif self.is_tv:
            return ArrType.Sonarr
        return None
    
    @property
    def external_id(self) -> Optional[str]:
        if self.is_movie:
            return self.media.get("tmdbId")
        if self.is_tv:
            return self.media.get("tvdbId")
        return None

    @property
    def requested_seasons(self) -> List[int]:
        """Parse requested seasons from extra field."""
        if not self.extra:
            return []
        for item in self.extra:
            if item.get("name") == "Requested Seasons":
                value = item.get("value", "")
                if value:
                    return [int(s.strip()) for s in value.split(",") if s.strip()]
        return []

    @property
    def is_valid(self) -> Optional[str]:
        return self.notification_type in [NotificationType.MEDIA_AUTO_APPROVED.name, NotificationType.MEDIA_APPROVED.name]

    @property
    def is_test(self) -> Optional[str]:
        return self.notification_type in [NotificationType.TEST_NOTIFICATION.name]

    @property
    def external_param(self) -> Optional[str]:
        """Build external_id:seasons format for Sonarr, or just external_id for Radarr."""
        if not self.external_id:
            return None
        
        if self.is_tv:
            seasons = self.requested_seasons
            if seasons:
                return f"{self.external_id}:{','.join(str(s) for s in seasons)}"
        return self.external_id

@dataclass
class SeerrConfig:
    Url: Optional[str] = field(
        default="http://localhost:5055",
        metadata={
            "name": "Seerr Server",
            "description": "URL used to connect to the Seerr server, including http(s)://, port, and urlbase if required"
        }
    )
    UrlFrom: Optional[str] = field(
        default_factory=lambda: YorznabClient().Url,
        metadata={
            "name": "Yorznab Server",
            "description": "Yorznab server URL as the Arr app sees it, including http(s)://, port, and urlbase if needed"
        }
    )
    ApiKey: Optional[str] = field(
        default=None,
        metadata={
            "required": True,
            "name": "API Key",
            "description": "The ApiKey generated by the Seerr app in Settings > General"
        }
    )

@dataclass
class SeerrClient(BaseClient[SeerrConfig]):
    
    def __init__(self):
        # Initialize _name and _config_file
        self._server_type = "Seerr"
        super().__init__(name=self.ServerType)

    class EndpointType(Enum):
        status = '/status'
        webhook = '/settings/notifications/webhook'
        
        def __str__(self):
            return self.value

    def GetEndpoint(self, endpoint) -> str:
        return self.UrlPath + str(endpoint)
    
    @property
    def Headers(self) -> dict[str, str]: return {"X-Api-Key": self.Config.ApiKey or ''}
    
    @property
    def DefaultUrl(self) -> str: return "http://localhost:5055"
    
    @property
    def ServerType(self) -> str: return self._server_type
    
    @property
    def ApiVersion(self) -> str: return '/api/v1'
    
    @property
    def UrlPath(self) -> str: return self.Url + self.ApiVersion

    @staticmethod
    def parse_payload(raw_payload: dict) -> WebhookPayload:
        """Parse raw webhook into dataclass."""
        return from_dict(
            data_class=WebhookPayload,
            data=raw_payload,
            config=Config(cast=[str])
        )

    @property
    def session(self) -> httpx.AsyncClient:
        """Get the session, always using singleton"""
        return self._get_session()

    async def status(self) -> dict[str, Any]:
        self.LOGGER.info(f"🛜 Pinging {self.ServerName} server")
        resp = await self.session.get(self.GetEndpoint(self.EndpointType.status), headers=self.Headers, timeout=self.TIMEOUT_DEFAULT)
        resp.raise_for_status()
        result = resp.json()
        self.LOGGER.info(f"✅ Received ping response from {self.ServerName} server")
        return result

    async def configure_webhook(self) -> bool:
        webhook_url = self.Config.UrlFrom + RouteHandler.WEBHOOK
        auth_header = KeyStore.get_key('WEBHOOK_KEY')

        # The exact JSON template with formatting preserved
        json_payload_str = """{
  "notification_type": "{{notification_type}}",
  "event": "{{event}}",
  "subject": "{{subject}}",
  "message": "{{message}}",
  "image": "{{image}}",
  "{{media}}": {
    "media_type": "{{media_type}}",
    "tmdbId": "{{media_tmdbid}}",
    "tvdbId": "{{media_tvdbid}}",
    "status": "{{media_status}}",
    "status4k": "{{media_status4k}}"
  },
  "{{request}}": {
    "request_id": "{{request_id}}",
    "requestedBy_email": "{{requestedBy_email}}",
    "requestedBy_username": "{{requestedBy_username}}",
    "requestedBy_avatar": "{{requestedBy_avatar}}",
    "requestedBy_settings_discordId": "{{requestedBy_settings_discordId}}",
    "requestedBy_settings_telegramChatId": "{{requestedBy_settings_telegramChatId}}"
  },
  "{{issue}}": {
    "issue_id": "{{issue_id}}",
    "issue_type": "{{issue_type}}",
    "issue_status": "{{issue_status}}",
    "reportedBy_email": "{{reportedBy_email}}",
    "reportedBy_username": "{{reportedBy_username}}",
    "reportedBy_avatar": "{{reportedBy_avatar}}",
    "reportedBy_settings_discordId": "{{reportedBy_settings_discordId}}",
    "reportedBy_settings_telegramChatId": "{{reportedBy_settings_telegramChatId}}"
  },
  "{{comment}}": {
    "comment_message": "{{comment_message}}",
    "commentedBy_email": "{{commentedBy_email}}",
    "commentedBy_username": "{{commentedBy_username}}",
    "commentedBy_avatar": "{{commentedBy_avatar}}",
    "commentedBy_settings_discordId": "{{commentedBy_settings_discordId}}",
    "commentedBy_settings_telegramChatId": "{{commentedBy_settings_telegramChatId}}"
  },
  "{{extra}}": []
}"""

        payload = {
            "enabled": True,
            "types": NotificationType.MEDIA_APPROVED.value + NotificationType.MEDIA_AUTO_APPROVED.value,
            "options": {
                "webhookUrl": webhook_url,
                "authHeader": auth_header,
                "jsonPayload": json_payload_str,
            }
        }

        self.LOGGER.info(f"🔧 Configuring the webhook for {self.ServerName}")
        response = await self.session.post(
            f"{self.UrlPath}{self.EndpointType.webhook}",
            json=payload,
            headers=self.Headers,
            timeout=self.TIMEOUT_DEFAULT
        )
        response.raise_for_status()
        self.LOGGER.info(f"✅ Configured the webhook successfully")
        return response.json()
        